### ISSUE TITLE
Libraries are outdated

### ISSUE THREAD

**Issue by guhehe** [yeokm1/docs-to-pdf-converter#1]

**Comment by yeokm1** [comment]
Ok noted. I'll look into updating the libraries. I'll probably use Maven now to track and update the required libraries.

 In the meantime, are there any problems you have encountered so far with the existing version?

**Comment by yeokm1** [comment]
I have updated all the libraries to their latest versions.

You can find the new release [here](https://github.com/yeokm1/docs-to-pdf-converter/releases/tag/v1.8)

**Comment by guhehe** [comment]
Woah! Thank you very much!

**Comment by guhehe** [comment]
No problem at all, I've seen some bugs in the conversion, but I know that it's the fault of the libraries themselves.

**Comment by ashwini35** [comment]
hi yeokm1 thanks a lot for sharing this, came across this utility, and found code and used libraries are old/outdated. but still does the work nicely :) . wanted to mention that when i convert pptx to pdf, any image which are at bottom or embedded in footer of ppt is not coming in pdf. I hope these are limitations, can u please confirm? Cant we call office native libraries/macros from java just to save these file in pdf format .(i mean leveraging save as option of office document pragmatically ), is this doable ? as per you what are the dependencies if we try this ?

**Comment by yeokm1** [comment]
Hi @ashwini35 

As I mentioned in the readme, I'm not maintaining this project any longer but I'm open to pull requests or help from others to help maintain.

Better libraries may need to be paid for like Aspose.

As for native APIs, I don't think Microsoft Office has one. You can possibly try libreoffice. https://ask.libreoffice.org/en/question/2641/convert-to-command-line-parameter/
