### ISSUE TITLE
pixel perfect conversion using docx2pdf

### ISSUE THREAD

**Issue by AlJohri** [yeokm1/docs-to-pdf-converter#22]
Just wanted to link an alternative command line tool / python library just for the `docx` use case. It uses Microsoft Word's APIs to provide a perfect conversion to PDF and works on both MacOS and Windows: https://github.com/AlJohri/docx2pdf

**Comment by yeokm1** [comment]
Thanks @AlJohri but I don't think creating an issue here is an appropriate place to raise awareness of your project.
